version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/images/ci/jdk"
      - "/images/ci/graalvm"
      - "/images/ci/krakend"
      - "/images/ci/node"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
